### ISSUE TITLE
创建一个可以用 Issue 发布文章的 GitHub Pages 模板

### ISSUE THREAD

**Issue by fjvi** [fjvi/blog#1]
## 创建一个可以用 Issue 发布文章的 GitHub Pages 模板

**目标：** 利用 GitHub Issues 作为内容来源，自动生成并发布静态博客页面。

**步骤：**

### 1. 创建 GitHub 仓库

* 创建一个新的 GitHub 仓库，例如：`my-issue-blog`。
* 初始化仓库并添加 `README.md` 文件。

### 2. 配置 GitHub Pages

* 进入仓库设置页面，找到 "Pages" 选项。
* 选择 `main` 分支作为发布源，并选择根目录 `/ (root)`。
* 点击 "Save" 保存设置。

### 3. 创建 GitHub Actions 工作流

* 在仓库根目录下创建 `.github/workflows/sync-issues.yml` 文件。
* 编写 GitHub Actions 脚本，实现以下功能：
    * 监听 Issues 的创建、修改、关闭等事件。
    * 将 Issues 内容转换为 Markdown 文件，并保存到 `_posts` 文件夹。
    * 自动提交更改到仓库并触发 GitHub Pages 构建。

**示例 GitHub Actions 脚本:**

```yaml
name: Sync GitHub Issues to Pages

on:
  issues:
    types: [opened, edited, closed]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert Issue to Markdown
        uses: actions/github-script@v5
        with:
          script: |
            const issue = context.payload.issue
            const fs = require('fs')
            const path = `_posts/${issue.created_at.split('T')[0]}-${issue.number}.md`
            const content = `---
title: "${issue.title}"
date: "${issue.created_at}"
tags: ${JSON.stringify(issue.labels.map(label => label.name))}
---

${issue.body}
`
            fs.writeFileSync(path, content)

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _posts/
          git commit -m "Sync GitHub Issues"
          git push
```

### 4. 创建 Jekyll 模板

* 在仓库根目录下创建 `_config.yml` 文件，配置 Jekyll 的基本设置。
* 创建 `_layouts/default.html` 文件，作为博客页面的默认布局。
* 创建 `_includes/header.html` 和 `_includes/footer.html` 文件，用于定义页面的头部和尾部。
* 创建 `index.html` 文件，作为博客的首页。

**示例 `_config.yml` 文件:**

```yaml
title: My Issue Blog
description: A blog powered by GitHub Issues
theme: minima
```

**示例 `_layouts/default.html` 文件:**

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ page.title }}</title>
  </head>
  <body>
    {% include header.html %}
    {{ content }}
    {% include footer.html %}
  </body>
</html>
```

**示例 `index.html` 文件:**

```html
---
layout: default
---

<h1>Latest Posts</h1>

<ul>
  {% for post in site.posts %}
    <li>
      <h2><a href="{{ post.url }}">{{ post.title }}</a></h2>
      <p>{{ post.date | date_to_string }}</p>
      <p>{{ post.excerpt }}</p>
    </li>
  {% endfor %}
</ul>
```

### 5. 发布文章

* 在 GitHub 仓库中创建一个新的 Issue。
* 在 Issue 标题中输入文章标题，在 Issue 内容中输入文章内容。
* 添加标签对文章进行分类。
* 提交 Issue，GitHub Actions 会自动将其转换为 Markdown 文件并发布到 GitHub Pages。

### 6. 访问博客

* 打开浏览器，访问 `https://<username>.github.io/my-issue-blog` 即可查看你的博客。

**其他说明：**

* 你可以根据自己的需求修改 Jekyll 模板和 GitHub Actions 脚本。
* 你可以使用其他静态网站生成器，例如 Hugo 或 Hexo。
* 你可以为博客添加评论功能、搜索功能等。

希望以上内容能够帮助你创建一个可以用 Issue 发布文章的 GitHub Pages 模板。
